#require 'jekyll/scholar'
# require 'jekyll-scholar-extras'
require 'jekyll/scholar/extras'
# require '/Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-extras-0.1.3/lib/jekyll/scholar/extras.rb'
# require_all '/Library/Ruby/Gems/2.0.0/gems/jekyll-scholar-extras-0.1.3/'
